replicaCount: 2
image:
  repository: 760370564012.dkr.ecr.us-east-1.amazonaws.com/pavel-hello-world-node-images
  tag: "8e3aa46" # is it take latest, or tag must be named as LATEST?
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
