# TODO: upgrade to several deployments configuration
nameOverride: ""
fullnameOverride: ""
replicaCount: 2
msName: "webapp"
image:
  repository: 760370564012.dkr.ecr.us-east-1.amazonaws.com/pavel-hello-world-node-images
  tag: "45930d9"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
cronScale:
  enabled: true
  preWarmReplicas: 6
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - hello-world-node
          topologyKey: "topology.kubernetes.io/zone"
