{{- if .Values.cronScale.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hello-world-node.fullname" . }}-scale-up
spec:
  schedule: "0 7 * * *" # 10:00 ISR = 07:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - |
              kubectl scale deployment {{ include "hello-world-node.fullname" . }} --replicas={{ .Values.cronScale.preWarmReplicas}}
          restartPolicy: OnFailure
{{- end }}