{{- if .Values.cronScale.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hello-world-node.fullname" . }}-scale-up
spec:
  schedule: "50 6 * * *" # 09:50 ISR = 06:50 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - |
              kubectl scale deployment {{ include "hello-world-node.fullname" . }} --replicas={{ .Values.cronScale.preWarmReplicas}}   
              sleep 2100 # 30 min block HPA
          restartPolicy: OnFailure
{{- end }}

# TODO: forgot SA
# error: no objects passed to scale deployments.apps "hwn-test-hello-world-node-webapp" is forbidden: User "system:serviceaccount:hwn-test:default" cannot get resource " ││ deployments" in API group "apps" in the namespace "hwn-test"      