{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hello-world-node.fullname" . }}
  annotations:
    # Ускоряем масштабирование
    autoscaling.alpha.kubernetes.io/behavior: |
      {
        "scaleUp": {
          "stabilizationWindowSeconds": 60,
          "policies": [
            {
              "type": "Pods",
              "value": 4,
              "periodSeconds": 15
            }
          ]
        }
      }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hello-world-node.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    # Добавляем метрику очереди (если применимо)
    - type: External
      external:
        metric:
          name: requests_per_second
          selector:
            matchLabels:
              app: {{ include "hello-world-node.name" . }}
        target:
          type: AverageValue
          averageValue: 1000
{{- end }}