apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-world-node.fullname" . }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "hello-world-node.fullname" . }}