# protects against other disruptions ... drain, eviction... 
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-world-node.fullname" . }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "hello-world-node.selectorLabels" . | nindent 6 }}