apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-node.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
      {{- include "hello-world-node.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
