name: Update Helm Chart

on:
  workflow_run:
    workflows: ["Build and Push Node.js to ECR"]
    types:
      - completed

jobs:
  update-chart:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install proper yq (Go version)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Get image tag from previous workflow
        id: get-tag
        run: |
          echo "IMAGE_TAG=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Update Helm chart values
        working-directory: ./charts/hwn
        run: |
          # Update using proper yq syntax
          yq eval -i '.image.tag = "${{ steps.get-tag.outputs.IMAGE_TAG }}"' values.yaml
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "CI: Update image tag to ${{ steps.get-tag.outputs.IMAGE_TAG }} [skip ci]"
          git push

      - name: Show changes
        run: |
          echo "Updated values.yaml:"
          cat ./charts/hwn/values.yaml